//! Owner vectors copied from `ducktape-modules` at
//! `1c6ec6c7bf4e5b788f78651353430442b264e9cb`,
//! `crates/modules/apps/chat/src/contract_golden.rs`.
//!
//! These are immutable owner bytes, not values generated by this app test.

use super::{Block, ChatMsg, PostPolicy, Span};

const CREATE_CHANNEL: &[u8] =
    br#"{"create_channel":{"channel_id":"general","name":"General","post_policy":"open"}}"#;
const REGISTER_HOOK: &[u8] =
    br#"{"register_hook":{"channel_id":"general","module_id":"automations"}}"#;
const POST_MESSAGE: &[u8] = br#"{"post_message":{"channel_id":"general","message_id":"m1","blocks":[{"paragraph":[{"text":"hello","marks":[]}]}],"thread":null}}"#;

#[test]
fn owner_vectors_pin_chat_message_bytes() {
    let messages = [
        (
            ChatMsg::CreateChannel {
                channel_id: "general".into(),
                name: "General".into(),
                post_policy: PostPolicy::Open,
            },
            CREATE_CHANNEL,
        ),
        (
            ChatMsg::RegisterHook {
                channel_id: "general".into(),
                module_id: "automations".into(),
            },
            REGISTER_HOOK,
        ),
        (
            ChatMsg::PostMessage {
                channel_id: "general".into(),
                message_id: "m1".into(),
                blocks: vec![Block::Paragraph(vec![Span {
                    text: "hello".into(),
                    marks: Vec::new(),
                }])],
                thread: None,
            },
            POST_MESSAGE,
        ),
    ];
    for (message, bytes) in messages {
        assert_eq!(super::encode_msg(&message), bytes);
        assert_eq!(super::decode_msg(bytes).unwrap(), message);
    }
}
